# Generated by Django 4.1 on 2024-10-24 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounting_ai", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FraudDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_fraudulent", models.BooleanField(default=False)),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="AccountingRecord",
        ),
        migrations.AddField(
            model_name="frauddetection",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounting_ai.transaction",
            ),
        ),
    ]
