# Generated by Django 4.1 on 2024-10-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smartcontracts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="smartcontract",
            name="contract_name",
        ),
        migrations.RemoveField(
            model_name="smartcontract",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="smartcontract",
            name="user",
        ),
        migrations.AddField(
            model_name="smartcontract",
            name="code",
            field=models.TextField(default="N/A"),
        ),
        migrations.AddField(
            model_name="smartcontract",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="smartcontract",
            name="name",
            field=models.CharField(default="Default Name", max_length=255),
        ),
        migrations.AlterField(
            model_name="smartcontract",
            name="contract_address",
            field=models.CharField(max_length=42),
        ),
    ]
